### ISSUE TITLE
null response from server

### ISSUE THREAD

**Issue by linusblom** [chas-academy/09-recipe-book-ulmez#1]
Seem that the server responds with null, no matter what the search query is, and no results is therefor shown.

**Comment by ulmez** [comment]
The url address was changed for the images to the recipes, but I have fixed that now. Also I had no more time than to manage fix search on ingredients in the recipes. So if you search milk in the search field you will get all recipes that has milk as ingredient in it.

**Comment by ulmez** [comment]
I can't fix filtering on recipes on meal type, allergies and cooking time because the api "themealdb" don't have options to do that, but I can fix to be able to save recipe list. Why I have not done it yet is because I hadn't enough time to fix it, and it came new assignments continually so I haven't either had the time to fix it yet.

But I can fix being able to save recipe list.

**Comment by linusblom** [comment]
I see. Add the ability to save recipes to a list and it will be ok.

**Comment by ulmez** [comment]
I have fixed the ability to save recipes to a list now. You may have to clear the cookies at the site before it will work properly, because I had a dummy cookie first that I never had the time to fix. Now I have fixed so the list will be stored in a cookie properly.
